name: Maven Compile Template
on:
  workflow_call:
    inputs:
      java:
        description: 'Java version'
        default: '8'
        required: true
        type: string
jobs:
  maven-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check env 
        run: echo ${{ inputs.java }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java }}'
          cache: 'maven'
          server-id: 'github' # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Check maven 
        run: java -version && mvn -version && cat /home/runner/.m2/settings.xml
      - name: Compile with maven
        run: mvn clean compile -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}