name: Maven Compile Template
env:
  JAVA_VERSION: '8'
on: workflow_call
jobs:
  maven-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '$JAVA_VERSION'
          cache: 'maven'
          server-id: 'github' # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Check maven 
        run: java -version && mvn -version && cat /home/runner/.m2/settings.xml
      - name: Compile with maven
        run: mvn clean compile -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
