name: GitHub Release Template
on: workflow_call
jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest tag
        run: |
         # fetch all tags
         git fetch --tags
         
         # create variables
         LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
         GITHUB_REL_NAME=$(echo v${LATEST_TAG##*-})
         
         # echo VAR=$VAL on GITHUB_ENV
         echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
         echo "GITHUB_REL_NAME=$GITHUB_REL_NAME" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.LATEST_TAG }} # tag name (see run script)
          release_name: ${{ env.GITHUB_REL_NAME }} # release name (see run script)
          body_path: RELEASE-NOTES.md # default RELEASE-NOTES document
          draft: false # default
          prerelease: false # default