name: Maven Release Template
on:
  workflow_call:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string
      java:
        description: "Java version"
        required: true
        type: string
jobs:
  maven-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java }}'
          cache: 'maven'
          server-id: 'github' # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Check maven 
        run: java -version && mvn -version && cat /home/runner/.m2/settings.xml
      - name: Check inputs
        run: |
          [[ "${{ inputs.version }}" ]] || { echo "version input is empty" ; exit 1; }
        shell: bash        
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Release with maven
        if: github.ref_name != github.event.repository.default_branch # Not on default branch
        run: mvn -DskipTests -Dmaven.test.skip=true -B -Dresume=false release:prepare release:perform -Darguments=-DskipTests -Dmaven.test.skip=true -Dmaven.site.skip=true -Dmaven.site.deploy.skip=true  -DreleaseVersion=${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
